Repository hiba9201/NoIdeasChatBot, pull requests merged in 2019-09, with the labels that each got.

#1 Декомпозиция
  src/main/java/ConsoleInterface.java
  src/main/java/DialogLogic.java
  src/main/java/Storage.java
  src/main/java/TimeManagementChatBot.java
Labels: enhancement

#2 devConsole fixes
  src/main/java/ConsoleInterface.java
  src/main/java/DialogLogic.java
  src/main/java/Storage.java
  src/main/java/TimeManagementChatBot.java
Labels: bug

#3 Json
  NoIdeasChatBot.iml
  pom.xml
  src/main/java/FileManager.java
  src/main/java/ScheduleEvent.java
  src/main/java/TimeManagementChatBot.java
  src/main/java/User.java
  user1.json
Labels: enhancement

#4 Dev conosle
  src/main/java/AnswerGenerator.java
  src/main/java/ConsoleInterface.java
  src/main/java/DialogLogic.java
  src/main/java/Storage.java
  src/main/java/TimeManagementChatBot.java
Labels: enhancement

#6 Dev console tests
  src/test/java/TestAnswerGenerator.java
Labels: tests
