Repository hiba9201/NoIdeasChatBot, pull requests merged in 2019-10, with the labels that each got.

#10 Команда добавления события
  src/main/java/AnswerGenerator.java
  src/main/java/DialogLogic.java
  src/main/java/DialogMode.java
Labels: enhancement

#11 To telegram
  pom.xml
  src/main/java/AnswerGenerator.java
  src/main/java/Bot.java
  src/main/java/TimeManagementChatBot.java
Labels: enhancement

#12 Addition command
  NoIdeasChatBot.iml
  src/main/java/AdditionEvent.java
  src/main/java/AnswerGenerator.java
  src/main/java/FileManager.java
  target/classes/ical4j.properties
Labels: enhancement

#13 Фикс логики диалога:WIP
  src/main/java/AnswerGenerator.java
  src/main/java/DialogLogic.java
  src/test/java/TestAnswerGenerator.java
Labels: bug, enhancement

#17 Добавление тестов + hotfix
  src/main/java/DialogLogic.java
  src/test/java/TestAnswerGenerator.java
  src/test/java/TestDialogLogic.java
Labels: bug, tests

#18 Добавление тестов
  src/main/java/AnswerGenerator.java
  src/test/java/TestAnswerGenerator.java
Labels: tests

#20 Добавлен тест, что событие добавлено
  src/test/java/TestDialogLogic.java
Labels: tests

#19 Тесты на парсинг даты и времени
  src/test/java/TestAdditionEvent.java
Labels: tests

#21 тест обновлен
  src/test/java/TestDialogLogic.java
Labels: tests

#23 Fix (incorrect date + test)
  src/main/java/AdditionEvent.java
  src/main/java/AnswerGenerator.java
  src/test/java/TestAdditionEvent.java
Labels: tests

#24 Fix file manager
  src/main/java/AdditionEvent.java
  src/main/java/AnswerGenerator.java
  src/main/java/EmptyCalendarException.java
  src/main/java/FileManager.java
  src/test/java/TestFileManager.java
Labels: enhancement, tests

#25 Dev
  src/main/java/AdditionEvent.java
  src/main/java/AnswerGenerator.java
  src/main/java/EmptyCalendarException.java
  src/main/java/FileManager.java
  src/test/java/TestAdditionEvent.java
  src/test/java/TestFileManager.java
Labels: enhancement, tests
